accounts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('sign_up/', sign_up, name='signup'),
    path('sign_in/', sign_in, name='signin'),
    path('sign_out/', sign_out, name='signout'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('battle/', include(('battle.urls', 'battle'), namespace='battle')),
    path('crm_customers/', include(('crm_customers.urls', 'crm_customers'), namespace='crm_customers')),
    path('crm_employees/', include(('crm_employees.urls', 'crm_employees'), namespace='crm_employees')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'shop.views.handler404'

shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('shop/', shop, name='shop'),
    path('product/<int:pk>/', product, name='product-details'),
    path('cart/', cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('profile/', user_profile, name='user-profile'),
    path('support/', support, name='support'),
    path('search/', search, name='search'),
]

shop/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class MenuTagModel(models.Model):
    name = models.CharField(max_length=20)
    link = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'menu tag'
        verbose_name_plural = 'Menu tags'


class DiscountModel(models.Model):
    code = models.CharField(max_length=13)
    value = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], help_text='In percent')

    def __str__(self):
        return '{0} ({1}%)'.format(self.code, self.value)

    class Meta:
        ordering = ['value']
        verbose_name = 'discount'
        verbose_name_plural = 'Discounts'


class ProductCategoryModel(models.Model):
    category = models.CharField(max_length=15)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'product category'
        verbose_name_plural = 'Products category'


class ProductModel(models.Model):
    name = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    in_stock = models.BooleanField(default=False)
    description = models.TextField()
    category = models.ForeignKey(ProductCategoryModel, db_index=True, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='media/shop/products/')

    count = 1

    def get_count(self):
        return self.count

    def get_sum_price(self):
        return self.count * self.price

    def sum_in_cart(self):
        pass

    def __str__(self):
        return '{0}: {1}, {2}'.format(self.name, self.price, self.in_stock)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'Products'


class ProductAdditionalPhoto(models.Model):
    parent = models.ForeignKey(ProductModel, on_delete=models.PROTECT)
    photo = models.ImageField(upload_to='media/shop/products/')

    def __str__(self):
        return f'Product: {self.parent.name}'

    class Meta:
        verbose_name = 'product additional photo'
        verbose_name_plural = 'Products additional photo'


class OrderModel(models.Model):
    need_delivery = models.BooleanField(default=False)
    address = models.CharField(max_length=150)
    discount = models.ForeignKey(DiscountModel, db_index=True, on_delete=models.PROTECT)
    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    notes = models.TextField(blank=True)
    date_order = models.DateTimeField(auto_now_add=True)
    date_send = models.DateTimeField(auto_now=False, null=True, blank=True)

    STATUSES = [
        ('NEW', 'New order'),
        ('APR', 'Aprowed'),
        ('PAY', 'Payed'),
        ('CNL', 'Canceled'),
    ]
    status = models.CharField(choices=STATUSES, max_length=3, default='NEW')

    def __str__(self):
        return f'self.date_order | self.status | self.name: self.address, self.phone, self.email'

    class Meta:
        verbose_name = 'order'
        verbose_name_plural = 'Orders'


class OrderLineModel(models.Model):
    order = models.ForeignKey(OrderModel, db_index=True, on_delete=models.PROTECT)
    product = models.ForeignKey(ProductModel, db_index=True, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    count = models.IntegerField(validators=[MinValueValidator(1)], default=1)

    def __str__(self):
        return 'Order (ID {0}) {1}: {2}'.format(self.order.id, self.product.title, self.count)

    class Meta:
        verbose_name = 'order line'
        verbose_name_plural = 'Orders lines'

shop/forms.py
from django import forms


class SearchForm(forms.Form):
    question = forms.ChoiceField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type your kayword...'}))

shop/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.views import generic
from django.http import Http404

from shop.models import ProductModel

from shop.forms import SearchForm


# Create your views here.
def index(request, pk=None):
    products = ProductModel.objects.all()
    return render(request, 'shop/index.html', {'products': products})


def shop(request):
    return render(request, 'shop/shop.html')


def product(request, pk=None):
    result = prerender(request)
    if result:
        return result
    products = ProductModel.objects.filter(pk=pk)
    return render(request, 'shop/product-details.html', {'products': products})


def prerender(request):
    if request.GET.get('add_cart'):
        product_id = request.GET.get('add_cart')
        get_object_or_404(ProductModel, pk=product_id)
        cart_info = request.session.get('cart_info', {})
        count = cart_info.get(product_id, 0)
        count += 1
        cart_info.update({product_id: count})
        request.session['cart_info'] = cart_info
        print(cart_info)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required(login_url='accounts:signin')
def cart(request):
    cart_info = request.session.get('cart_info')
    products = []
    if cart_info:
        for product_id in cart_info:
            # product = get_object_or_404(ProductModel, pk=product_id)
            try:
                product = ProductModel.objects.get(pk=product_id)
                product.count = cart_info[product_id]
                products.append(product)
            except ProductModel.DoesNotExist:
                raise Http404()
    context = {
        'products': products
    }
    return render(request, 'shop/cart.html', context=context)


@login_required(login_url='accounts:signin')
def checkout(request):
    return render(request, 'shop/checkout.html')


def support(request):
    return render(request, 'shop/support.html')


@login_required(login_url='accounts:signin')
def user_profile(request):
    return render(request, 'shop/user/profile.html')


def search(request):
    search = SearchForm(request.GET)
    if search.is_valid():
        question = search.cleaned_data['question']
        products = ProductModel.objects.filter(
            Q(name__icontains=question) | Q(price__icontains=question) |
            Q(category__icontains=question)
        )

        context = {
            'products': products,
            'question': question,
        }

        return render(request, 'shop/search_results.html', context=context)
    else:
        search = SearchForm()
    return render(request, 'shop/index.html')

def handler404(request, exception):
    return render(request, 'shop/404.html', status=404)

shop/templates/shop/inc/_footer.html
{% load static %}
<!-- ##### Newsletter Area Start ##### -->
{% if request.user.is_authenticated %}
{% else %}
<section class="newsletter-area section-padding-100-0">
    <div class="container">
        <div class="row align-items-center text-center">
            <!-- Newsletter Text -->
            <div class="col-12 col-lg-6 col-xl-7">
                <div class="newsletter-text mb-100">
                    <h2>Register for a <span>25% Discount</span> on first order</h2>
                    <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                </div>
            </div>
            <!-- Newsletter Form -->
            <div class="col-12 col-lg-6 col-xl-5">
                <div class="newsletter-form mb-100">
                    <a href="{% url 'accounts:signup' %}" class="btn amado-btn mb-15">Register</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}
<!-- ##### Newsletter Area End ##### -->

<!-- ##### Footer Area Start ##### -->
<footer class="footer_area clearfix">
    <div class="container">
        <div class="row align-items-center">
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-4">
                <div class="single_widget_area">
                    <!-- Logo -->
                    <div class="footer-logo mr-50">
                        <a href="index.html"><img src="{% static 'img/core-img/logo2.png' %}" alt=""></a>
                    </div>
                    <!-- Copywrite Text -->
                    <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Template adaptation and backend (Django) by Eugene Chernyshev. <script>document.write(new Date().getFullYear());</script>. Template by: <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-8">
                <div class="single_widget_area">
                    <!-- Footer Menu -->
                    <div class="footer_menu">
                        <nav class="navbar navbar-expand-lg justify-content-end">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                            <div class="collapse navbar-collapse" id="footerNavContent">
                                <ul class="navbar-nav ml-auto">

                                    <li class="nav-item">
                                        <a class="nav-link" href="index.html">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="shop.html">Shop</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="product-details.html">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="cart.html">Cart</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="checkout.html">Checkout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ##### Footer Area End ##### -->

shop/templates/shop/inc/_header.html
{% load static %}
{% load menu_tags %}
<header class="header-area clearfix">
    <!-- Close Icon -->
    <div class="nav-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <!-- Logo -->
    <div class="logo">
        <a href="{% url 'shop:home' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
    </div>
    <!-- Amado Nav -->
    <nav class="amado-nav">
        <ul>
            <li class=""><a href="{% url 'shop:home' %}">Home</a></li>
            <li><a href="{% url 'shop:shop' %}">Shop</a></li>
        </ul>
        <!-- Cart Menu -->
        <div class="cart-fav-search mb-100">
            <a href="#" class="search-nav"><img src="{% static 'img/core-img/search.png' %}" alt=""> Search</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'shop:cart' %}" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> Cart <span>({{ count_in_cart }})</span></a>
            <a href="#" class="fav-nav"><img src="{% static 'img/core-img/favorites.png' %}" alt=""> Favourite</a>
            {% else %}
            {% endif %}
        </div>
    </nav>
    <!-- Button Group -->
    <div class="amado-btn-group mt-30 mb-50">
        <a href="{% url 'shop:user-profile' %}" class="btn amado-btn mb-15">Profile</a>
        <a href="{% url 'shop:support' %}" class="btn amado-btn active">Support</a>
    </div>
    <!-- Social Button -->
    <div class="social-info d-flex justify-content-between">
        <a href="https://www.linkedin.com/feed/"><i class="fa fa-linkedin" aria-hidden="true" target="_blank"></i></a>
        <a href="https://github.com/Eugene-and-sandbox"><i class="fa fa-github" aria-hidden="true" target="_blank"></i></a>
        <a href="https://www.facebook.com/ychernyshev"><i class="fa fa-facebook" aria-hidden="true" target="_blank"></i></a>
        <!-- <a href="#"><i class="fa fa-youtube" aria-hidden="true"></i></a> -->
    </div>
</header>

shop/templates/shop/inc/breadcrumps.html
<div class="row">
    <div class="col-12">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mt-50">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Furniture</a></li>
                <li class="breadcrumb-item"><a href="#">Chairs</a></li>
                <li class="breadcrumb-item active" aria-current="page">white modern chair</li>
            </ol>
        </nav>
    </div>
</div>