accounts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('sign_up/', sign_up, name='signup'),
    path('sign_in/', sign_in, name='signin'),
    path('sign_out/', sign_out, name='signout'),
]

crm_customers/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('price/', price, name='price'),
    path('rules/', rules, name='rules'),
    path('guarantee/', guarantee, name='guarantee'),
    path('reviews/', reviews, name='reviews'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),

    # User account
    path('dashboard/', dashboard, name='dashboard'),
    path('toorderabox/', to_order_a_box, name='toorderabox'),
    path('delivertheparcel/', deliver_the_parcel, name='delivertheparcel'),
    path('ordershystory/', orders_hystory, name='ordershystory'),
    path('useraccountsettings/', user_account_settings, name='useraccountsettings'),
    path('myreviews/', my_reviews, name='myreviews'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('battle/', include(('battle.urls', 'battle'), namespace='battle')),
    path('crm_customers/', include(('crm_customers.urls', 'crm_customers'), namespace='crm_customers')),
    path('crm_employees/', include(('crm_employees.urls', 'crm_employees'), namespace='crm_employees')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'shop.views.handler404'

shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('shop/', shop, name='shop'),
    path('product/<int:pk>/', product, name='product-details'),
    path('cart/', cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('profile/', user_profile, name='user-profile'),
    path('support/', support, name='support'),
    path('search/', search, name='search'),
]

crm_customers/models.py
from django.db import models

# Create your models here.

crm_customers/forms.py
from django import forms

crm_customers/views.py
from collections import defaultdict
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from accounts.models import MyUser
from crm_employees.models import DeliveryParcelModel, BoxOrderModel

from crm_employees.views import BoxOrderForm


def index(request):
    return render(request, 'crm_customers/index.html')


def price(request):
    return render(request, 'crm_customers/index.html')


def rules(request):
    return render(request, 'crm_customers/rules.html')


def guarantee(request):
    return render(request, 'crm_customers/guarantee.html')


def reviews(request):
    return render(request, 'crm_customers/reviews.html')


def contacts(request):
    return render(request, 'crm_customers/contacts.html')


def about(request):
    return render(request, 'crm_customers/about.html')


@login_required(login_url='accounts:signin')
def dashboard(request):
    return render(request, 'crm_customers/user_account/dashboard.html')


@login_required(login_url='accounts:signin')
def to_order_a_box(request):
    initial = {
        'email': request.user,
    }
    if request.method == 'POST':
        form = BoxOrderForm(request.POST, initial='email')
        if form.is_valid():
            BoxOrderModel.objects.create(**form.cleaned_data)
            return redirect('ordershystory')
    else:
        form = BoxOrderForm()
    return render(request, 'crm_customers/user_account/to_order_a_box.html', {'form': form})


@login_required(login_url='accounts:signin')
def deliver_the_parcel(request):
    return render(request, 'crm_customers/user_account/deliver_the_parcel.html')


@login_required(login_url='accounts:signin')
def orders_hystory(request):
    user_deliveries = DeliveryParcelModel.objects.filter(email__exact=request.user.email)
    user_boxes = BoxOrderModel.objects.filter(email__exact=request.user.email)

    context = {
        'user_deliveries': user_deliveries,
        'user_boxes': user_boxes,
    }
    return render(request, 'crm_customers/user_account/orders_hystory.html', context=context)


@login_required(login_url='accounts:signin')
def user_account_settings(request):
    account_info = MyUser.objects.filter(email__exact=request.user.email)

    context = {
        'account_info': account_info,
    }

    return render(request, 'crm_customers/user_account/user_account_settings.html', context=context)


@login_required(login_url='accounts:signin')
def my_reviews(request):
    return render(request, 'crm_customers/user_account/my_reviews.html')

crm_customers/templates/crm_customers/inc/_footer.html
<footer class="site-footer">
        <div class="container">
          <div class="row">
            <div class="col-lg-3">
              <h2 class="footer-heading mb-4">About as</h2>
              <p>We are a young and promising team of specialists in their field. We are guaranteed to deliver your parcels and constantly strengthen our partnership with you. </p>
              <ul class="list-unstyled social">
                <li><a href="www.linkedin.com/in/ychernyshev"><span class="icon-linkedin" target="_blank"></span></a></li>
                <li><a href="https://github.com/Eugene-and-sandbox/eugene-chernyshev-portfolio"><span class="icon-github" target="_blank"></span></a></li>
                <li><a href="https://www.facebook.com/ychernyshev"><span class="icon-facebook" target="_blank"></span></a></li>
              </ul>
            </div>
            <div class="col-lg-8 ml-auto">
              <div class="row">
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-4">Menu</h2>
                  <ul class="list-unstyled">
                    <li><a href="{% url 'crm_customers:home' %}">Home</a></li>
                    <li><a href="{% url 'crm_customers:price' %}">Price</a></li>
                    <li><a href="{% url 'crm_customers:rules' %}">Import rules</a></li>
                    <li><a href="{% url 'crm_customers:guarantee' %}">Guarantee</a></li>
                    <li><a href="{% url 'crm_customers:reviews' %}">Feedback</a></li>
                    <li><a href="{% url 'crm_customers:contacts' %}">Contacts</a></li>
                  </ul>
                </div>
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-4">Rosourse</h2>
                  <ul class="list-unstyled">
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Import rules</a></li>
                  </ul>
                </div>
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-4">Support</h2>
                  <ul class="list-unstyled">
                    <li><a href="#">Answers</a></li>
                    <li><a href="#">Infografics</a></li>
                    <li><a href="#">Forum</a></li>
                    <li><a href="#">Feedback</a></li>
                    <li><a href="#">Request a call</a></li>
                  </ul>
                </div>
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-4">Our company</h2>
                  <ul class="list-unstyled">
                    <li><a href="{% url 'crm_customers:about' %}">About as</a></li>
                    <li><a href="#">Our success in numbers</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
              <div class="border-top pt-5">
                <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Eugene Chernyshev</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
              </div>
            </div>

          </div>
        </div>
      </footer>

crm_customers/templates/crm_customers/inc/_topnav.html
  <header class="site-navbar site-navbar-target" role="banner">

    <div class="container">
        <div class="row align-items-center position-relative">

            <div class="col-3">
                <div class="site-logo">
                    <a href="{% url 'crm_customers:home' %}"><strong>Delivery Inc.</strong></a>
                </div>
            </div>

            <div class="col-9  text-right">

                <span class="d-inline-block d-lg-none"><a href="#" class=" site-menu-toggle js-menu-toggle py-5 "><span
                            class="icon-menu h3 text-black"></span></a></span>

                <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                    <ul class="site-menu main-menu js-clone-nav ml-auto ">
                        <li class="active"><a href="{% url 'crm_customers:home' %}" class="nav-link">Home</a></li>
                        <li><a href="{% url 'crm_customers:price' %}" class="nav-link">Price</a></li>
                        <li><a href="{% url 'crm_customers:rules' %}" class="nav-link">Rules</a></li>
                        <li><a href="{% url 'crm_customers:guarantee' %}" class="nav-link">Guarantee</a></li>
                        <li><a href="{% url 'crm_customers:reviews' %}" class="nav-link">Reviews</a></li>
                        <li><a href="{% url 'crm_customers:contacts' %}" class="nav-link">Contacts</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown ml-5">
                            <!-- Example single danger button -->
                            <div class="btn-group">
                                <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                    {{ request.user.name }} {{ request.user.surname }}
                                </button>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'crm_customers:dashboard' %}">Reports</a>
                                    <a class="dropdown-item" href="{% url 'crm_customers:toorderabox' %}">Order
                                        a box</a>
                                    <a class="dropdown-item" href="{% url 'crm_customers:delivertheparcel' %}">Order a delivery</a>
                                    <a class="dropdown-item" href="{% url 'crm_customers:ordershystory' %}">Orders history</a>
                                    <a class="dropdown-item"
                                        href="{% url 'crm_customers:useraccountsettings' %}">Profile settings</a>
                                    <div class="dropdown-divider"></div>
                                    <a href="{% url 'accounts:signout' %}" class="dropdown-item btn btn-danger btn-block">Sign Out</a>
                                </div>
                            </div>
                        </li>
                        {% else %}
                        <li class="ml-5"><a href="{% url 'crm_customers:dashboard' %}" class="nav-link">Perconal page</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>


        </div>
    </div>

</header>