accounts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('sign_up/', sign_up, name='signup'),
    path('sign_in/', sign_in, name='signin'),
    path('sign_out/', sign_out, name='signout'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('battle/', include(('battle.urls', 'battle'), namespace='battle')),
    path('crm_customers/', include(('crm_customers.urls', 'crm_customers'), namespace='crm_customers')),
    path('crm_employees/', include(('crm_employees.urls', 'crm_employees'), namespace='crm_employees')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'shop.views.handler404'

shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('shop/', shop, name='shop'),
    path('product/<int:pk>/', product, name='product-details'),
    path('cart/', cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('profile/', user_profile, name='user-profile'),
    path('support/', support, name='support'),
    path('search/', search, name='search'),
]

accounts/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, Group
)
from django.contrib.auth.models import PermissionsMixin


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    USER_ROLE = [
        ('CL', 'Client'),
        ('AD', 'Admin'),
    ]
    user_role = models.CharField(choices=USER_ROLE, max_length=2, default='CL')

    USER_POSITION = [
        ('MEN', 'Manager'),
        ('CEO', 'Chief Executive Officer'),
        ('FOU', 'Founder'),
        ('CLI', 'Client')
    ]
    user_position_1 = models.CharField(choices=USER_POSITION, max_length=3)
    user_position_2 = models.CharField(choices=USER_POSITION, max_length=3, blank=True)
    user_position_3 = models.CharField(choices=USER_POSITION, max_length=3, blank=True)
    name = models.CharField(max_length=30, blank=True)
    surname = models.CharField(max_length=30, blank=True)
    address = models.CharField(max_length=150, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    picture = models.ImageField(upload_to='media/images/users/', blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

   

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.name} {self.surname}, {self.address}, {self.phone}, {self.email}'

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


    

accounts/forms.py
from xml.dom.minidom import Attr
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'User email'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


class UserProfileUpdateForm(forms.Form):
    email = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label='',
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password confirmation'}))
    name = forms.CharField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Name'}))
    surname = forms.CharField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Surname'}))
    address = forms.CharField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Address'}))
    phone = forms.CharField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Phone'}))

accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

from accounts.admin import UserCreationForm
from accounts.forms import UserLoginForm, UserProfileUpdateForm
from portfolio.forms import ContactForm

from accounts.models import MyUser
from portfolio.models import ExamplePreviewModel, ExampleCategoryModel


def index(request):
    return render(request, 'accounts/sign-in.html')


def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:signin')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/sign-up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('portfolio:e_examples')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/sign-in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('accounts:signin')


# @login_required(login_url='accounts:signin')
# def user_profile(request, email=None):
#     profile_info = MyUser.objects.all()
    

#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             send_mail(form.cleaned_data['name'], form.cleaned_data['content'], 'eugene_chernyshev@ukr.net', ['eugene_chernyshev@ukr.net'], fail_silently=False)
#             return redirect('accounts:profile')
#     else:
#         form = ContactForm()

#     context = {
#         'title': 'Ptofile',
#         'profile_info': profile_info,
#         'form': form,
#     }
#     return render(request, 'accounts/user-profile.html', context=context)

accounts/templates/accounts/inc/_footer.html
<footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Company
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            About Us
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Team
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Products
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Blog
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Pricing
          </a>
        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-dribbble"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-twitter"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-instagram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-pinterest"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            Copyright © <script>
              document.write(new Date().getFullYear())
            </script> Soft by Creative Tim.
          </p>
        </div>
      </div>
    </div>
  </footer>

accounts/templates/accounts/inc/_scripts.html
<!--   Core JS Files   -->
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script>
  var win = navigator.platform.indexOf('Win') > -1;
  if (win && document.querySelector('#sidenav-scrollbar')) {
    var options = {
      damping: '0.5'
    }
    Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
  }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js' %}"></script>
<!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/soft-ui-dashboard.min.js' %}"></script>

accounts/templates/accounts/inc/_topnav.html
<nav
    class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
    <div class="container-fluid pe-0">
        <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="{% url 'portfolio:home' %}">
            eugene_chernyshev.lviv.ua
        </a>
        <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav mx-auto ms-xl-auto me-xl-7">
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center me-2 active" aria-current="page"
                        href="../pages/dashboard.html">
                        <i class="fa fa-chart-pie opacity-6 text-dark me-1"></i>
                        Examples
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link me-2" href="../pages/profile.html">
                        <i class="fa fa-user opacity-6 text-dark me-1"></i>
                        Try yours fortune
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link me-2" href="{% url 'accounts:signout' %}">
                        <i class="fas fa-user-circle opacity-6 text-dark me-1"></i>
                        Sign Out
                    </a>
                </li>
            </ul>
            <li class="nav-item d-flex align-items-center">
                <a class="btn btn-round btn-sm mb-0 btn-outline-primary me-2" target="_blank"
                    href="{% url 'portfolio:home' %}">Eugene portfolio</a>
            </li>
            <ul class="navbar-nav d-lg-block d-none">
                <li class="nav-item">
                    <a href="https://www.creative-tim.com/product/soft-ui-dashboard"
                        class="btn btn-sm btn-round mb-0 me-1 bg-gradient-dark">Download CV</a>
                </li>
            </ul>
        </div>
    </div>
</nav>