crm_employees/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('', index, name='home'),
    path('users/', users_table, name='users'),
    path('customer_card/<int:pk>/', customer_card, name='customercard'),
    path('customer_card/update_info/', update_sender_info, name='updatesenderinfo'),

    path('boxorder/', box_order, name='boxorder'),
    path('deliveryparcel/', delivery_parcel, name='deliveryparcel'),
    path('history/orders/', orders_history, name='ordershistory'),
    path('history/orders/order_details/<int:pk>', order_details, name='orderdetails'),
    # path('history/returned/', returned_parcels, name='returned'),
    path('new_sender/', new_sender, name='newsender'),
    path('new_ricipient/', new_recipient, name='newrecipient'),
    path('documentation/', documentation, name='documentation'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('battle/', include(('battle.urls', 'battle'), namespace='battle')),
    path('crm_customers/', include(('crm_customers.urls', 'crm_customers'), namespace='crm_customers')),
    path('crm_employees/', include(('crm_employees.urls', 'crm_employees'), namespace='crm_employees')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'shop.views.handler404'

shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('shop/', shop, name='shop'),
    path('product/<int:pk>/', product, name='product-details'),
    path('cart/', cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('profile/', user_profile, name='user-profile'),
    path('support/', support, name='support'),
    path('search/', search, name='search'),
]

crm_employees/forms.py
from cProfile import label
import email
from turtle import width
from django import forms

from crm_employees.models import CustomerRecipientInfoModel, BoxOrderModel, \
DeliveryTariffModel, CustomerDiscountModel, CourierTariffModel
from accounts.models import MyUser


class UpdateUserInfoForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    surname = forms.CharField(label='Surname', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(label='Phone', widget=forms.TextInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label='Address', widget=forms.TextInput(attrs={'class': 'form-control'}))


class BoxOrderForm(forms.Form):
    customer = forms.ModelChoiceField(queryset=MyUser.objects.all(), label='', empty_label='Choose sender', widget=forms.Select(attrs={'class': 'form-control w-75'}))
    email = forms.CharField(label='', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    size_ten = forms.IntegerField(label='10', widget=forms.NumberInput(attrs={'class': 'form-control mt-3 w-75', 'min': 0, 'placeholder': 'Box of 10 kg'}))
    size_twenty = forms.IntegerField(label='20', widget=forms.NumberInput(attrs={'class': 'form-control mt-3 w-75', 'min': 0, 'placeholder': 'Box of 20 kg'}))
    size_thirty = forms.IntegerField(label='30', widget=forms.NumberInput(attrs={'class': 'form-control mt-3 w-75', 'min': 0, 'placeholder': 'Box of 30 kg'}))


class DeliveryParcelForm(forms.Form):
    sender = forms.ModelChoiceField(queryset=MyUser.objects.all(), label='', empty_label='Senders', widget=forms.Select(attrs={'class': 'form-control w-75'}))
    recipient = forms.ModelChoiceField(queryset=CustomerRecipientInfoModel.objects.all(), label='', empty_label='Recipients', widget=forms.Select(attrs={'class': 'form-control mt-3 w-75'}))
    weight = forms.IntegerField(label='', widget=forms.NumberInput(attrs={'class': 'form-control mt-3 w-75'}))
    width = forms.IntegerField(label='', widget=forms.NumberInput(attrs={'class': 'form-control mt-3 w-75'}))
    height = forms.IntegerField(label='', widget=forms.NumberInput(attrs={'class': 'form-control mt-3 w-75'}))
    length = forms.IntegerField(label='', widget=forms.NumberInput(attrs={'class': 'form-control mt-3 w-75'}))
    price = forms.ModelChoiceField(queryset=DeliveryTariffModel.objects.all(), label='', empty_label='Tariff', widget=forms.Select(attrs={'class': 'form-control mt-3 w-75'}))
    discount = forms.ModelChoiceField(queryset=CustomerDiscountModel.objects.all(), label='', empty_label='Discount', widget=forms.Select(attrs={'class': 'form-control mt-3 w-75'}))
    courier = forms.ModelChoiceField(queryset=CourierTariffModel.objects.all(), label='', empty_label='Courier', widget=forms.Select(attrs={'class': 'form-control mt-3 w-75'}))


class AddNewRecipientForm(forms.Form):
    parent_sender = forms.ModelChoiceField(queryset=MyUser.objects.all(), label='', empty_label='Choose sender', widget=forms.Select(attrs={'class': 'form-control'}))
    name = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}))
    surname = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Surname'}))
    phone = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}))
    email = forms.CharField(label='', required=False, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    address = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}))

crm_employees/views.py
from datetime import date, datetime
from multiprocessing import context
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from pkg_resources import require

from accounts.admin import UserCreationForm
from crm_employees.forms import UpdateUserInfoForm, BoxOrderForm, DeliveryParcelForm, AddNewRecipientForm
from portfolio.forms import ContactForm

from accounts.models import MyUser
from crm_employees.models import BoxOrderModel, DeliveryParcelModel, CustomerRecipientInfoModel


@login_required(login_url='accounts:signin')
def index(request):
    parcels_count = DeliveryParcelModel.objects.filter().count()
    boxes_count = BoxOrderModel.objects.filter().count()
    customers_count = MyUser.objects.filter().count()

    last_boxes = BoxOrderModel.objects.order_by('-ordering_date')[:5]
    last_boxes_paginator = Paginator(last_boxes, 4)
    last_boxes_number = request.GET.get('page')
    last_boxes_numbers = last_boxes_paginator.get_page(last_boxes_number)

    last_deliveries = DeliveryParcelModel.objects.order_by('-ordering_date')[:5]
    last_deliveries_paginator = Paginator(last_deliveries, 5)
    last_deliveries_number = request.GET.get('page')
    last_deliveries_obj = last_deliveries_paginator.get_page(last_deliveries_number)

    context = {
        'title': 'Dashboard',
        'parcels_count': parcels_count,
        'boxes_count': boxes_count,
        'customers_count': customers_count,
        'last_boxes_numbers': last_boxes_numbers,
        'last_deliveries_obj': last_deliveries_obj,
    }

    return render(request, 'crm_employees/dashboard.html', context=context)


@login_required(login_url='accounts:signin')
def users_table(request):
    users = MyUser.objects.all()
    context = {
        'users': users,
        'title': 'Users table',
    }
    return render(request, 'crm_employees/users.html', context=context)


@login_required(login_url='accounts:signin')
def customer_card(request, pk=None):
    customer_info = MyUser.objects.filter(pk=pk)
    customer_orders = DeliveryParcelModel.objects.filter(email__exact=request.user.email)
    customer_orders_pagination = Paginator(customer_orders, 3)
    customer_orders_nums = request.GET.get('page')
    customer_orders_obj = customer_orders_pagination.get_page(customer_orders_nums)

    context = {
        'customer_info': customer_info,
        'customer_orders': customer_orders,
        'customer_orders_obj': customer_orders_obj,
    }

    return render(request, 'crm_employees/customer_card.html', context=context)

@login_required(login_url='accounts:signin')
def profile(request):
    profile_info = MyUser.objects.all()

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            send_mail(form.cleaned_data['name'], form.cleaned_data['content'], 'eugene_chernyshev@ukr.net', ['eugene_chernyshev@ukr.net'], fail_silently=False)
            return redirect('accounts:profile')
    else:
        form = ContactForm()

    context = {
        'title': 'Employee profile',
        'profile_info': profile_info,
        'form': form,
    }
    return render(request, 'crm_employees/profile.html', context=context)


@login_required(login_url='accounts:signin')
def update_sender_info(request, pk=None):
    user = request.user
    if request.method == 'POST':
        update_user_form = UpdateUserInfoForm(request.POST, initial={
                    'email': user.email, 
                    'name': user.name, 
                    'surname': user.surname,
                    'phone': user.phone,
                    'address': user.address
                })
        if update_user_form.is_valid():      
            update_user_form.save()
            return redirect('crm_employees:profile')
    else:
        update_user_form = UpdateUserInfoForm()
    return render(request, 'crm_employees/updates/sender_info_update.html', {'update_user_form': update_user_form})
        


@login_required(login_url='accounts:signin')
def box_order(request):
    if request.method == 'POST':
        form = BoxOrderForm(request.POST)
        if form.is_valid():
            BoxOrderModel.objects.create(**form.cleaned_data)
            messages.success(request, 'Order has been saved')
            return redirect('crm_employees:boxorder')
        else:
            messages.error(request, 'Something went wrong')
    else:
        form = BoxOrderForm()
    return render(request, 'crm_employees/box_order.html', {'form': form, 'title': 'Order a Box'})


@login_required(login_url='accounts:signin')
def delivery_parcel(request):
    if request.method == 'POST':
        form = DeliveryParcelForm(request.POST)
        if form.is_valid():
            DeliveryParcelModel.objects.create(**form.cleaned_data)
            messages.success(request, 'Order saved')
            return redirect('crm_employees:deliveryparcel')
        else:
            messages.error(request, 'Something went wrong')
    else:
        form = DeliveryParcelForm()
    return render(request, 'crm_employees/delivery_parcel.html', {'form': form, 'title': 'Delivery Parcel'})


@login_required(login_url='accounts:signin')
def orders_history(request):
    user_photo = MyUser.objects.all()

    box_orders = BoxOrderModel.objects.order_by('-ordering_date')
    box_orders_pagination = Paginator(box_orders, 20)
    box_order_number = request.GET.get('page')
    box_order_obj = box_orders_pagination.get_page(box_order_number)

    delivery_orders = DeliveryParcelModel.objects.order_by('-ordering_date')
    delivery_orders_pagination = Paginator(delivery_orders, 20)
    delivery_orders_number = request.GET.get('page')
    delivery_orders_obj = delivery_orders_pagination.get_page(delivery_orders_number)

    context = {
        'title': 'Orders history',
        'box_order_obj': box_order_obj,
        'delivery_orders': delivery_orders,
        'delivery_orders_obj': delivery_orders_obj,
        'user_photo': user_photo,
    }
    return render(request, 'crm_employees/orders_history.html', context=context)


@login_required(login_url='accounts:signin')
def order_details(request, pk=None):
    box_details = BoxOrderModel.objects.filter(pk=pk)
    delivery_details = DeliveryParcelModel.objects.filter(pk=pk)

    context = {
        'box_details': box_details,
        'delivery_details': delivery_details,
        'title': 'Order Details',
    }

    return render(request, 'crm_employees/order_details.html', context=context)


@login_required(login_url='accounts:signin')
def returned_parcels(request):
    return render(request, 'crm_employees/returned_parcels.html', {'title': 'Returned Parcels'})


@login_required(login_url='accounts:signin')
def new_sender(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = UserCreationForm()
    return render(request, 'crm_employees/new_sender.html', {'form': form, 'title': 'Add new sender'})


@login_required(login_url='accounts:signin')
def new_recipient(request):
    if request.method == 'POST':
        form = AddNewRecipientForm(request.POST)
        if form.is_valid():
            CustomerRecipientInfoModel.objects.create(**form.cleaned_data)
            return redirect('crm_employees:newrecipient')
    else:
        form = AddNewRecipientForm()
    return render(request, 'crm_employees/new_recipient.html', {'form': form, 'title': 'Add new recipient'})


def documentation(request):
    return render(request, 'crm_employees/documentation.html', {'title': 'Documentation'})


def handler404(request, exception):
    return render(request, 'crm_employees/404.html', status=404)

crm_employees/templates/crm_employees/box_order.html
{% extends 'crm_employees/_base.html' %}
{% url 'crm_employees:boxorder' as boxorder %}

{% block title %}{{ title }}{% endblock %}
{% block content %}

<div class="row mt-4">
  <div class="col-12">
    <div class="card mb-4 p-3">
      <div class="card-header pb-0">
        <h6>Authors table</h6>
      </div>
      <div class="card-body px-0 pt-0 pb-2">
        <div class="table-responsive p-0">
          <form action="" method="post">
            {% csrf_token %}
            <label for="">Sender info</label>
            <p>{{ form.customer }}</p>
            <label for="">Number of boxes 10 kg</label>
            <p>{{ form.size_ten }}</p>
            <label for="">Number of boxes 20 kg</label>
            <p>{{ form.size_twenty }}</p>
            <label for="">Number of boxes 30 kg</label>
            <p>{{ form.size_thirty }}</p>
            {% for item in form %}
            {{ item.customer }}
            {{ item.sender.address }}
            {% endfor %}
            <button type="submit" class="btn bg-gradient-primary mt-3">Save order</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'crm_employees/inc/_side-panel.html' %}

{% include 'crm_employees/inc/_footer.html' %}
{% endblock %}

crm_employees/templates/crm_employees/breadcrumbs.html
{% if self.get_ancestors|length > 1 %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ self.title }}</li>
    </ol>
  </nav>
{% endif %}

crm_employees/templates/crm_employees/customer_card.html
{% extends 'crm_employees/_base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block content %}

<div class="row mt-4">
    <div class="col-12">
        {% for item in customer_info %}
        <div style="position: relative" class="card mb-4 p-3 mt-5">
            {% if item.picture.url is not none %}
            <img style="position: absolute; top: -5rem; left: 50%; border-radius: 50%; box-shadow: -.1rem 0rem .9rem 0 rgba(0, 0, 0, .5)"
                src="{{ item.picture.url }}" alt="picture" width="150">
            {% else %}
            <img style="position: absolute; top: 0; left: 50%; border: .1rem solid #f6f6f6; border-radius: 50%;"
                src="{% static 'accounts/img/default_image.png' %}" alt="picture">
            {% endif %}
            <div class="card-header pb-0">
                <h6>{{ item.name }} {{ item.surname }} Card</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
                <div class="row">
                    <div class="table-responsive p-0 col-md-5">
                        <table class="table">
                            <tbody>
                            <tbody>
                                <tr>
                                    <th colspan="2">
                                        <p>Sender info</p>
                                    </th>
                                </tr>
                            </tbody>
                            <tr>
                                <th>Name:</th>
                                <th>{{ item.name }} {{ item.surname }}</th>
                            </tr>
                            <tr>
                                <th>Phone</th>
                                <th>{{ item.phone }}</th>
                            </tr>
                            <tr>
                                <th>Second Phone:</th>
                                <th></th>
                            </tr>
                            <tr>
                                <th>Email:</th>
                                <th>{{ item.email }}</th>
                            </tr>
                            <tr>
                                <th>Address:</th>
                                <th>{{ item.address }}</th>
                            </tr>
                            <tr>
                                <th>ID card:</th>
                                <th></th>
                            </tr>
                            <tr>
                                <td>
                                    <a href="#" class="btn btn-info">Change sender data</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-7">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th colspan="5">Last Orders</th>
                                </tr>
                            </thead>
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        Track number</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        Recipient info</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Cost
                                    </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        Discount</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in customer_orders %}
                                <tr>
                                    <th scope="row" class="text-xs text-secondary font-weight-bold mb-0">{{ item.id }}
                                    </th>
                                    <th scope="row" class="text-xs text-secondary font-weight-bold mb-0">
                                        <a
                                            href="{% url 'crm_employees:orderdetails' item.pk %}">{{ item.intarnational_track_number }}</a>
                                    </th>
                                    <th class="align-middle">
                                        <div class="d-flex px-2 py-1">
                                            <div>
                                                {% if item.customer.picture.url is not none %}
                                                <img src="{{ item.recipient.picture.url }}"
                                                    class="avatar avatar-sm me-3" alt="user1">
                                                {% else %}

                                                {% endif %}
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-sm">{{ item.recipient.name }}
                                                    {{ item.recipient.surname }}</h6>
                                                <p class="text-xs text-secondary mb-0">{{ item.recipient.phone }}
                                                </p>
                                                <p class="text-xs text-secondary mb-0">{{ item.recipient.email }}
                                                </p>
                                                <p class="text-xs text-secondary mb-0">{{ item.recipient.address }}
                                                </p>
                                            </div>
                                        </div>
                                    </th>
                                    <th class="text-xs text-secondary font-weight-bold mb-0">{{ item.total_amount }}
                                    </th>
                                    <th class="text-xs text-secondary font-weight-bold mb-0">{{ item.discount.value }}%
                                    </th>
                                    <th class="text-xs text-secondary font-weight-bold mb-0">
                                        {% if item.completed_at is not none %}
                                        <span class="badge badge-sm bg-gradient-success">Delivered</span>
                                        {% else %}
                                        <span class="badge badge-sm bg-gradient-secondary">in delivery</span>
                                        {% endif %}
                                    </th>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <nav class="mx-auto" aria-label="Page navigation example mt-4">
                            <ul class="pagination">
                                {% if customer_orders_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ customer_orders_obj.previous_page_number }}"
                                        aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                {% endif %}
                                {% for page in customer_orders_obj.paginator.page_range %}
                                <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}
                                {% if customer_orders_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ customer_orders_obj.paginator.num_pages }}"
                                        aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                <hr />
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="home-tab" data-bs-toggle="tab"
                            data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane"
                            aria-selected="true">Recipients</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="profile-tab" data-bs-toggle="tab"
                            data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane"
                            aria-selected="false">Complaints</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="contact-tab" data-bs-toggle="tab"
                            data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane"
                            aria-selected="false">Feedback</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="contact-tab" data-bs-toggle="tab"
                            data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane"
                            aria-selected="false">Consultations</button>
                    </li>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel"
                            aria-labelledby="home-tab" tabindex="0">...</div>
                        <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab"
                            tabindex="0">...</div>
                        <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab"
                            tabindex="0">...</div>
                        <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab"
                            tabindex="0">...</div>
                    </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% include 'crm_employees/inc/_side-panel.html' %}

{% include 'crm_employees/inc/_footer.html' %}
{% endblock %}

crm_employees/templates/crm_employees/delivery_parcel.html
{% extends 'crm_employees/_base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="row mt-4">
    <div class="col-12">
        <div class="card mb-4 p-3">
            <div class="card-header pb-0">
                <h6>Authors table</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
                <div class="table-responsive p-0">
                    <form action="" method="post">
                        {% csrf_token %}
                        <label for="">Sender info</label>
                        <p>{{ form.sender }}</p>
                        <a href="#" class="btn btn-white btn-xs" onClick="window.open('{% url "crm_employees:newsender" %}','pagename','resizable,height=560,width=670'); return false;">Add new sender</a><noscript>You need Javascript to use the previous link or use <a href="{% url 'crm_employees:newsender' %}" target="_blank">Add new sender</a></noscript>
                        <p><label for="">Recipient info</label></p>
                        <p>{{ form.recipient }}</p>
                        <a href="#" class="btn btn-white btn-xs" onClick="window.open('{% url "crm_employees:newrecipient" %}','pagename','resizable,height=560,width=670'); return false;">Add new recipient</a><noscript>You need Javascript to use the previous link or use <a href="{% url 'crm_employees:newrecipient' %}" target="_blank">Add new recipient</a></noscript>
                        <p><label for="">Weight</label></p>
                        <p>{{ form.weight }}</p>
                        <label for="">Width</label>
                        <p>{{ form.width }}</p>
                        <label for="">Height</label>
                        <p>{{ form.height }}</p>
                        <label for="">Length</label>
                        <p>{{ form.length }}</p>
                        <label for="">Choice delivery tariff</label>
                        <p>{{ form.price }}</p>
                        <label for="">Discount <span class="text-sm">(0% by default)</span></label>
                        <p>{{ form.discount }}</p>
                        <label for="">Courier <span class="text-sm">(0$ by default)</span></label>
                        <p>{{ form.courier }}</p>
                        <button type="submit" class="btn bg-gradient-primary mt-3">Save order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'crm_employees/inc/_side-panel.html' %}

{% include 'crm_employees/inc/_footer.html' %}
{% endblock %}

crm_employees/templates/crm_employees/new_recipient.html
{% extends 'crm_employees/_mini_window_base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="d-flex align-items-center justify-content-center text-center" style="height: 590px">
    <form method="post">
        {% csrf_token %}
        <p>{{ form.parent_sender }}</p>
        <p>{{ form.name }}</p>
        <p>{{ form.surname }}</p>
        <p>{{ form.phone }}</p>
        <p>{{ form.email }}</p>
        <p>{{ form.address }}</p>
        <button type="submit" class="btn bg-gradient-primary mt-3" onclick="close_window(); return false">Create recipient</button>
    </form>
</div>
{% endblock %}

crm_employees/templates/crm_employees/new_sender.html
{% extends 'crm_employees/_mini_window_base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="d-flex align-items-center justify-content-center text-center" style="height: 590px">
    <form method="post">
        {% csrf_token %}
        <p>{{ form.email }}</p>
        <p>{{ form.password1 }}</p>
        <p>{{ form.password2 }}</p>
        <p>{{ form.name }}</p>
        <p>{{ form.surname }}</p>
        <p>{{ form.address }}</p>
        <p>{{ form.phone }}</p>
        <button type="submit" class="btn bg-gradient-primary mt-3" onclick="close_window(); return false">Create sender</button>
    </form>
</div>

<script>
    function closeWindow() {
        close()
    }
</script>
{% endblock %}

crm_employees/templates/crm_employees/returned_parcels.html
{% extends 'crm_employees/_base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}{% endblock %}

crm_employees/templates/crm_employees/users.html
{% extends 'crm_employees/_base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}{% endblock %}